import type { Metadata } from 'next'
import {Poppins} from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: {
    template: "Promarketing Test | %s",
    default: "Promarketing Test"
  },
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700']
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
